"""Auto-generated IRON GEMM design — BFP16, 64×64×32 tiles.

Generated by NPU Control Plane Compiler.
Target: II=1 via 4-accumulator interleaving + BFP16 emulation.
"""

import numpy as np
from ml_dtypes import bfloat16
import aie.iron as iron
from aie.iron import In, ObjectFifo, Out, Program, Runtime, Worker, kernels
from aie.iron.controlflow import range_
from aie.helpers.taplib import TensorTiler2D

# -- Configuration --
M_TILE = 64
K_TILE = 64
N_TILE = 32
N_AIE_ROWS = 4
N_AIE_COLS = 8
FIFO_DEPTH = 2

M_GLOBAL = M_TILE * N_AIE_ROWS
N_GLOBAL = N_TILE * N_AIE_COLS
K_GLOBAL = 4096
K_STEPS = K_GLOBAL // K_TILE

# Bank-aware buffer layout:
# A → bank 0, B → bank 1, C → bank 2
# Padding: M_pad=+1, N_pad=no

@iron.jit(aiecc_flags=[
    "--alloc-scheme=bank-aware",
    "--dynamic-objFifos",
])
def gemm_bfp16_optimized(A: In, B: In, C: Out):
    matmul_kernel = kernels.mm(
        dim_m=M_TILE, dim_k=K_TILE, dim_n=N_TILE,
        input_dtype=bfloat16, output_dtype=np.float32,
        use_chess=False,
        emulate_bf16_mmul_with_bfp16=True,
    )
    zero_kernel = matmul_kernel.zero

    # Buffer types
    A_l1_ty = np.ndarray[(M_TILE, K_TILE), np.dtype[bfloat16]]
    B_l1_ty = np.ndarray[(K_TILE, N_TILE), np.dtype[bfloat16]]
    C_l1_ty = np.ndarray[(M_TILE, N_TILE), np.dtype[np.float32]]
    A_l2_ty = np.ndarray[(M_TILE * K_TILE,), np.dtype[bfloat16]]
    B_l2_ty = np.ndarray[(K_TILE * N_TILE,), np.dtype[bfloat16]]
    C_l2_ty = np.ndarray[(M_TILE * N_TILE * N_AIE_ROWS,), np.dtype[np.float32]]

    # DMA streaming with BFP16 packing
    a_dims = [(M_TILE // 8, 8 * K_TILE), (K_TILE // 8, 8),
              (8, K_TILE), (8, 1)]
    b_dims = [(K_TILE // 8, 8 * N_TILE), (N_TILE // 8, 8),
              (8, N_TILE), (8, 1)]
    c_dims = [(M_TILE // 8, 8 * N_TILE), (8, 8),
              (N_TILE // 8, 8 * 8), (8, 1)]

    # ObjectFifo setup per row/column
    A_l3l2_fifos = [
        ObjectFifo(A_l2_ty, name=f"A_L3L2_{r}", depth=FIFO_DEPTH)
        for r in range(N_AIE_ROWS)
    ]
    B_l3l2_fifos = [
        ObjectFifo(B_l2_ty, name=f"B_L3L2_{c}", depth=FIFO_DEPTH)
        for c in range(N_AIE_COLS)
    ]

    A_l2l1_fifos = [
        f.cons().forward(obj_type=A_l1_ty, name=f"A_L2L1_{i}",
                         dims_to_stream=a_dims)
        for i, f in enumerate(A_l3l2_fifos)
    ]
    B_l2l1_fifos = [
        f.cons().forward(obj_type=B_l1_ty, name=f"B_L2L1_{i}",
                         dims_to_stream=b_dims)
        for i, f in enumerate(B_l3l2_fifos)
    ]

    # C: L1 → L2 → L3 per column
    C_l1l2_fifos = [[None] * N_AIE_COLS for _ in range(N_AIE_ROWS)]
    C_l2l3_fifos = []
    for col in range(N_AIE_COLS):
        of_ = ObjectFifo(C_l2_ty, name=f"C_L2L3_{col}", depth=FIFO_DEPTH)
        parts = of_.prod().join(
            [M_TILE * N_TILE * i for i in range(N_AIE_ROWS)],
            obj_types=[C_l1_ty] * N_AIE_ROWS,
            names=[f"C_L1L2_{col}_{row}" for row in range(N_AIE_ROWS)],
            depths=[FIFO_DEPTH] * N_AIE_ROWS,
        )
        for row in range(N_AIE_ROWS):
            C_l1l2_fifos[row][col] = parts[row]
        C_l2l3_fifos.append(of_)

    # Core compute function
    def core_fn(in_a, in_b, out_c, zero, matmul):
        for _ in range(1):
            elem_out = out_c.acquire(1)
            zero(elem_out)
            for _ in range_(K_STEPS):
                elem_a = in_a.acquire(1)
                elem_b = in_b.acquire(1)
                matmul(elem_a, elem_b, elem_out)
                in_a.release(1)
                in_b.release(1)
            out_c.release(1)

    # Worker grid: 4x8 = 32 tiles
    workers = Worker.grid(
        N_AIE_ROWS, N_AIE_COLS,
        lambda row, col: Worker(
            core_fn,
            [A_l2l1_fifos[row].cons(),
             B_l2l1_fifos[col].cons(),
             C_l1l2_fifos[row][col].prod(),
             zero_kernel,
             matmul_kernel],
            stack_size=0xD00,
        ),
    )

    # Runtime DMA scheduling
    rt = Runtime()
    with rt.sequence(
        np.ndarray[(M_GLOBAL * K_GLOBAL,), np.dtype[bfloat16]],
        np.ndarray[(K_GLOBAL * N_GLOBAL,), np.dtype[bfloat16]],
        np.ndarray[(M_GLOBAL * N_GLOBAL,), np.dtype[np.float32]],
    ) as (A_t, B_t, C_t):
        rt.start(*[w for row in workers for w in row])

        # Simplified DMA orchestration (fan-out A by row, B by col)
        for k_step in range(K_STEPS):
            tg = rt.task_group()
            for row in range(N_AIE_ROWS):
                rt.fill(A_l3l2_fifos[row].prod(), A_t, task_group=tg)
            for col in range(N_AIE_COLS):
                rt.fill(B_l3l2_fifos[col].prod(), B_t, task_group=tg)
                rt.drain(C_l2l3_fifos[col].cons(), C_t, wait=True, task_group=tg)

    return Program(iron.get_current_device(), rt).resolve_program()


# =============================================================================
# Benchmarking
# =============================================================================

if __name__ == "__main__":
    import argparse
    from aie.utils.hostruntime.argparse import add_compile_args, add_benchmark_args
    from aie.utils.hostruntime.cli import run_design_cli

    p = argparse.ArgumentParser(prog="GEMM BFP16 Optimized")
    add_compile_args(p, short_dev=None)
    add_benchmark_args(p)
    opts = p.parse_args()

    run_design_cli(gemm_bfp16_optimized, opts)
