/**
 * AIE2P BFP16 GEMM Micro-Kernel — Auto-generated by NPU Control Plane Compiler
 *
 * Dimensions:  M=64, K=64, N=32
 * μkernel:     8×8×8 (512 MACs/insn)
 * Interleave:  4-way accumulator
 * Target II:   1 (1.6 GFLOPS/tile theoretical)
 * BFP16:       Yes (2× throughput vs BF16)
 * Double-buf:  Yes
 * Banks:       A=bank0, B=bank1, C=bank2
 * Pad stride:  M=True, N=False
 *
 * Compile with:
 *   peano-clang++ --target=aie2-none-unknown-elf -std=c++20 -O2 \
 *       -DAIE2P_K_STEPS=64 -DAIE2P_M_TILE=64 \
 *       -DAIE2P_K_TILE=64 -DAIE2P_N_TILE=32
 */

#include <aie_api/aie.hpp>

using namespace aie;

// Compile-time constants (override with -D flags)
#ifndef AIE2P_M_TILE
#define AIE2P_M_TILE 64
#endif
#ifndef AIE2P_K_TILE
#define AIE2P_K_TILE 64
#endif
#ifndef AIE2P_N_TILE
#define AIE2P_N_TILE 32
#endif
#ifndef AIE2P_K_STEPS
#define AIE2P_K_STEPS 64
#endif

// Micro-kernel tile dimensions
constexpr int M_MICRO = 8;
constexpr int K_MICRO = 8;
constexpr int N_MICRO = 8;

// Derived constants
constexpr int M_ITERS = AIE2P_M_TILE / M_MICRO;   // 8
constexpr int N_ITERS = AIE2P_N_TILE / N_MICRO;   // 4
constexpr int INTERLEAVE = 4;

// Buffer sizes (in elements)
constexpr int A_ELEMS = AIE2P_M_TILE * AIE2P_K_TILE;   // 4096
constexpr int B_ELEMS = AIE2P_K_TILE * AIE2P_N_TILE;   // 2048
constexpr int C_ELEMS = AIE2P_M_TILE * AIE2P_N_TILE;   // 2048

/**
 * BFP16 GEMM tile: C[m_tile][n_tile] += A[m_tile][k_tile] × B[k_tile][n_tile]
 *
 * Input A, B: packed bfloat16 arrays (2 bytes/element)
 * Output C:  float array (4 bytes/element), accumulated in-place
 *
 * Uses BFP16 emulation with MacConfBFP576ACC2048 intrinsic for
 * 512 MACs per instruction (2× vs native BF16).
 */
void gemm_bfp16_tile_64x64x32(
    const bfloat16* restrict A_l1,   // [M_TILE][K_TILE] in L1 bank 0
    const bfloat16* restrict B_l1,   // [K_TILE][N_TILE] in L1 bank 1
    float* restrict C_l1,            // [M_TILE][N_TILE] in L1 bank 2
    int k_steps = AIE2P_K_STEPS
) {
    // Vector registers (512-bit): v0-v3 for double-buffered loads
::aie::vector<bfloat16, 32> va_load;   // v0: A operand (32×bf16 = 512b)
::aie::vector<bfloat16, 32> vb_load;   // v1: B operand
::aie::vector<bfloat16, 32> va_load2;  // v2: A double-buffer
::aie::vector<bfloat16, 32> vb_load2;  // v3: B double-buffer

// Accumulator registers: a0-a3 for interleaved mmul chains
::aie::accum<accfloat, 64> acc0;  // a0: chain 0
::aie::accum<accfloat, 64> acc1;  // a1: chain 1
::aie::accum<accfloat, 64> acc2;  // a2: chain 2
::aie::accum<accfloat, 64> acc3;  // a3: chain 3

// Temporary registers
::aie::vector<float, 16>   va_fp32;  // v4: A converted
::aie::vector<float, 16>   vb_fp32;  // v5: B converted
::aie::accum<accfloat, 64> acc_tmp; // a5: temp accumulator


    // Iterate over M and N micro-tile positions
    for (int mi = 0; mi < M_ITERS; mi++) {
        for (int ni = 0; ni < N_ITERS; ni++) {

            // Offset for this (mi, ni) micro-tile
            const int a_offset = mi * M_MICRO * AIE2P_K_TILE;
            const int b_offset = ni * N_MICRO;
            const int c_offset = mi * M_MICRO * AIE2P_N_TILE + ni * N_MICRO;

            // ================================================================
            // Inner K-loop with software pipelining
            // ================================================================
                        // Zero accumulators for this micro-tile
            acc0 = ::aie::zeros<accfloat, 64>();
            acc1 = ::aie::zeros<accfloat, 64>();
            acc2 = ::aie::zeros<accfloat, 64>();
            acc3 = ::aie::zeros<accfloat, 64>();

            // Prologue: pre-load first 3 operand pairs
            {
                const bfloat16* a_ptr = &A_l1[a_offset];
                const bfloat16* b_ptr = &B_l1[b_offset];
                va_load  = ::aie::load_v<bf16, 32>(a_ptr);
                vb_load  = ::aie::load_v<bf16, 32>(b_ptr);
                a_ptr += 32; b_ptr += N_MICRO;
                va_load2 = ::aie::load_v<bf16, 32>(a_ptr);
                vb_load2 = ::aie::load_v<bf16, 32>(b_ptr);
            }

            #pragma clang loop pipeline(enable)
            #pragma clang loop min_iteration_count(16)
            #pragma clang loop pipeline_initiation_interval(1)
            #pragma clang loop unroll_count(4)
            for (int k = 3; k < k_steps; k++) {
                const bfloat16* a_ptr = &A_l1[a_offset + k * 32];
                const bfloat16* b_ptr = &B_l1[b_offset + k * N_MICRO];

                // Load next operands (k + 3 ahead)
                va_load = ::aie::load_v<bf16, 32>(a_ptr);
                vb_load = ::aie::load_v<bf16, 32>(b_ptr);

                // Convert double-buffered operands to BFP16
                auto va_bfp = ::aie::to_float(va_load2);
                auto vb_bfp = ::aie::to_float(vb_load2);

                // BFP16 mmul (MacConfBFP576ACC2048) — rotate accumulators
                if ((k & 3) == 0)      acc0 = ::aie::mac(acc0, va_bfp, vb_bfp);
                else if ((k & 3) == 1) acc1 = ::aie::mac(acc1, va_bfp, vb_bfp);
                else if ((k & 3) == 2) acc2 = ::aie::mac(acc2, va_bfp, vb_bfp);
                else                    acc3 = ::aie::mac(acc3, va_bfp, vb_bfp);

                // Rotate double-buffer
                va_load2 = va_load;
                vb_load2 = vb_load;
            }

            // Epilogue: drain pipeline + reduce accumulators
            {
                auto va_bfp = ::aie::to_float(va_load2);
                auto vb_bfp = ::aie::to_float(vb_load2);
                acc1 = ::aie::mac(acc1, va_bfp, vb_bfp);
            }
            acc_tmp = ::aie::add(acc0, acc1);
            acc_tmp = ::aie::add(acc_tmp, acc2);
            acc_tmp = ::aie::add(acc_tmp, acc3);

            // Store to C (pack accfloat → float)
            float* c_ptr = &C_l1[c_offset];
            ::aie::store_v(c_ptr, acc_tmp.to_vector<float>());

        }
    }
}
